In [105]:
import pandas as pd
import numpy as np

In [216]:
df = pd.read_csv("../demo_dic/demo_dic_norms.csv")
df

        norms_id scale  raw  std interpretation
0   ita_all_norm    s1    0   10          basso
1   ita_all_norm    s1    1   10          basso
2   ita_all_norm    s1    2   10          basso
3   ita_all_norm    s1    3   10          basso
4   ita_all_norm    s1    4   10          basso
5   ita_all_norm    s2    0   10          basso
6   ita_all_norm    s2    1   30          medio
7   ita_all_norm    s2    2   50          medio
8   ita_all_norm    s2    3   70           alto
9   ita_all_norm    s2    4   90           alto
10  ita_all_norm    s3    0   10          basso
11  ita_all_norm    s3    1   30          medio
12  ita_all_norm    s3    2   50          medio
13  ita_all_norm    s3    3   70           alto
14  ita_all_norm    s3    4   90           alto
15  ita_all_clin    s1    0   10          basso
16  ita_all_clin    s1    1   10          basso
17  ita_all_clin    s1    2   10          basso
18  ita_all_clin    s1    3   10          basso
19  ita_all_clin    s1    4   10          basso
20  ita_all_clin    s2    0  110          medio
21  ita_all_clin    s2    1  130          medio
22  ita_all_clin    s2    2  150          medio
23  ita_all_clin    s2    3  170          medio
24  ita_all_clin    s2    4  190          medio
25  ita_all_clin    s3    0  110           alto
26  ita_all_clin    s3    1  130           alto
27  ita_all_clin    s3    2  150           alto
28  ita_all_clin    s3    3  170           alto
29  ita_all_clin    s3    4  190           alto

In [225]:
norms = df.pivot_table(index=['scale','raw'], columns=['norms_id'], values=['std','interpretation'], aggfunc=lambda x: x).reset_index()
norms

         scale raw interpretation                       std
norms_id             ita_all_clin ita_all_norm ita_all_clin ita_all_norm
0           s1   0          basso        basso           10           10
1           s1   1          basso        basso           10           10
2           s1   2          basso        basso           10           10
3           s1   3          basso        basso           10           10
4           s1   4          basso        basso           10           10
5           s2   0          medio        basso          110           10
6           s2   1          medio        medio          130           30
7           s2   2          medio        medio          150           50
8           s2   3          medio         alto          170           70
9           s2   4          medio         alto          190           90
10          s3   0           alto        basso          110           10
11          s3   1           alto        medio          130           30
12          s3   2           alto        medio          150           50
13          s3   3           alto         alto          170           70
14          s3   4           alto         alto          190           90

In [227]:
flatted = pd.DataFrame(norms.to_records())

In [228]:
import re
[ "_".join(re.findall(r'\b\w+\b', c))  for c in flatted.columns.values  ]

['index',
 'scale',
 'raw',
 'interpretation_ita_all_clin',
 'interpretation_ita_all_norm',
 'std_ita_all_clin',
 'std_ita_all_norm']

In [247]:
[ c+x for c,x in (norms.columns.get_level_values(0), norms.columns.get_level_values(0))    ]

ValueError: too many values to unpack (expected 2)

In [272]:
t = (5 - (1.95-(.93))) * (8.45/5)
1.26 + (.85*2)

2.96